name: Generate Version & Tag

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate semantic version + create tag
        id: semver
        uses: bitshifted/git-auto-semver@v1.1.0
        with:
          main_branch: main
          initial_version: 0.1.0
          create_tag: true
          tag_prefix: "v"
