- name: "Git Automatic Semantic Versioning"
  # You may pin to the exact commit or the version.
  # uses: bitshifted/git-auto-semver@f136eb2d08062ca75e92f2408e1e9ace385c7523
  uses: "bitshifted/git-auto-semver@v1.1.0"
  with:
    # Main branch for the repository
    main_branch: # optional, default is main
    # First version, defaults to 1.0.0
    initial_version: 0.1.0
    create_tag: true
    tag_prefix: "v"
